name: Java CI Practice

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
env:
  APP_NAME: JavaApp
  ENVIRONMENT: DEV

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Show Java version
        run: java -version

      - name: Show current directory
        run: pwd

      - name: Show project files
        run: ls -la

      - name: Compile Java
        run: javac App.java

      - name: Run Java application
        run: java App

      - name: Build completed
        run: echo "GitHub Actions CI build completed successfully!"


  test:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Test message
        run: echo "Test job started"

      - name: Check Java
        run: java -version

      - name: Test completed
        run: echo "Test job completed successfully"

  report:
    runs-on: ubuntu-latest

    needs: test

    if: always()

    steps:
      - name: Report started
        run: echo "Reporting job started"

      - name: Show test result
        run: echo "Test job finished"

      - name: Report completed
        run: echo "Reporting completed even if test failed"